
      <div class="footer-col">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1')->toHtml();?>
      </div>
      <div class="footer-col">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2')->toHtml();?>
      </div>
      <div class="footer-col">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-3')->toHtml();?>
      </div>
      <div class="footer-col">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-4')->toHtml();?>
      </div>
